# Generated by Django 3.2.8 on 2021-10-19 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
