# Generated by Django 3.2.8 on 2021-10-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='actors', to='movies.Actor'),
        ),
        migrations.DeleteModel(
            name='Actors_Movie',
        ),
    ]
