# Generated by Django 3.2.8 on 2021-10-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_allergy_allergy_product_image_nutrition_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='english_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='korean_name',
            field=models.CharField(max_length=30),
        ),
    ]
