# Generated by Django 3.2.8 on 2021-10-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211017_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy_product',
            old_name='allergy_id',
            new_name='allergy',
        ),
        migrations.RenameField(
            model_name='allergy_product',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nutrition_id',
            new_name='nutrition',
        ),
    ]
